### ISSUE TITLE
vagrant up amp fails to install java

### ISSUE THREAD

**Issue by murdoaird** [cloudsoft/amp-vagrant#5]
On running `vagrant up amp` the following error is thrown:

Bringing machine 'amp' up with 'virtualbox' provider...
==> amp: Importing base box 'ubuntu/wily64'...
==> amp: Matching MAC address for NAT networking...
==> amp: Setting the name of the VM: amp
==> amp: Clearing any previously set forwarded ports...
==> amp: Clearing any previously set network interfaces...
==> amp: Preparing network interfaces based on configuration...
    amp: Adapter 1: nat
    amp: Adapter 2: hostonly
==> amp: Forwarding ports...
    amp: 8081 (guest) => 8081 (host) (adapter 1)
    amp: 22 (guest) => 2222 (host) (adapter 1)
==> amp: Running 'pre-boot' VM customizations...
==> amp: Booting VM...
==> amp: Waiting for machine to boot. This may take a few minutes...
    amp: SSH address: 127.0.0.1:2222
    amp: SSH username: vagrant
    amp: SSH auth method: private key
    amp: Warning: Remote connection disconnect. Retrying...
    amp: Warning: Remote connection disconnect. Retrying...
    amp: Warning: Remote connection disconnect. Retrying...
    amp:
    amp: Vagrant insecure key detected. Vagrant will automatically replace
    amp: this with a newly generated keypair for better security.
    amp:
    amp: Inserting generated public key within guest...
    amp: Removing insecure key from the guest if it's present...
    amp: Key inserted! Disconnecting and reconnecting using new SSH key...
==> amp: Machine booted and ready!
==> amp: Checking for guest additions in VM...
==> amp: Setting hostname...
==> amp: Configuring and enabling network interfaces...
==> amp: Mounting shared folders...
    amp: /vagrant => /Users/murdoaird/Documents/workspace/amp-vagrant
==> amp: Running provisioner: shell...
    amp: Running: inline script
==> amp: Running provisioner: shell...
    amp: Running: inline script
==> amp: Reading package lists...
==> amp: Building dependency tree...
==> amp:
==> amp: Reading state information...
==> amp: The following extra packages will be installed:
==> amp:   ca-certificates-java java-common libpcsclite1
==> amp: Suggested packages:
==> amp:   default-jre equivs pcscd openjdk-8-jre-jamvm libnss-mdns fonts-dejavu-extra
==> amp:   fonts-ipafont-gothic fonts-ipafont-mincho ttf-wqy-microhei ttf-wqy-zenhei
==> amp:   fonts-indic
==> amp: The following NEW packages will be installed:
==> amp:   ca-certificates-java java-common libpcsclite1 openjdk-8-jre-headless
==> amp: 0 upgraded, 4 newly installed, 0 to remove and 0 not upgraded.
==> amp: Need to get 27.0 MB of archives.
==> amp: After this operation, 99.6 MB of additional disk space will be used.
==> amp: Get:1 http://archive.ubuntu.com/ubuntu/ wily/main ca-certificates-java all 20140324 [12.3 kB]
==> amp: Get:2 http://archive.ubuntu.com/ubuntu/ wily/main java-common all 0.52 [131 kB]
==> amp: Get:3 http://archive.ubuntu.com/ubuntu/ wily/main libpcsclite1 amd64 1.8.14-1ubuntu1 [21.4 kB]
==> amp: Err http://archive.ubuntu.com/ubuntu/ wily-updates/universe openjdk-8-jre-headless amd64 8u66-b17-1
==> amp:   404  Not Found [IP: 91.189.88.152 80]
==> amp: Err http://security.ubuntu.com/ubuntu/ wily-security/universe openjdk-8-jre-headless amd64 8u66-b17-1
==> amp:   404  Not Found [IP: 91.189.88.152 80]
==> amp: Fetched 164 kB in 8s (20.4 kB/s)
==> amp: E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/universe/o/openjdk-8/openjdk-8-jre-headless_8u66-b17-1_amd64.deb  404  Not Found [IP: 91.189.88.152 80]
==> amp:
==> amp: E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

----------------------END OF ERROR----------------------

It looks like the attempted URL (Failed to fetch http://security.ubuntu.com/ubuntu/pool/universe/o/openjdk-8/openjdk-8-jre-headless_8u66-b17-1_amd64.deb) isn't available

I fixed the error using these steps but it didn't feel like altering 'servers.yaml' to do this was the proper solution:

Connect to VM and re-create:

- `vagrant ssh amp`

- `sudo apt-get install --yes openjdk-8-jre-headless`

To fix:
- `sudo vim /etc/apt/sources.list`
- add this line to the file `deb http://us.archive.ubuntu.com/ubuntu wily main universe`
- `sudo apt-get update`

Try again:
`sudo apt-get install --yes openjdk-8-jre-headless` - success

What's the best solution? Should we be upgrading to latest ubuntu?

WDYT @johnmccabe @drigodwin?

**Comment by johnmccabe** [comment]
Hi @murdoaird the issue here is that you've currently got a stale `ubuntu/wily64` cached in your system, you can fix as follows:
1. Destroy the current boxes
    ```
    vagrant destroy
    ```
2. Update your cached box
    ```
    vagrant box update
    ```
3. Start your box
    ```
    vagrant up
    ```

There are 2 config options in the `server.yaml` that are currently disabled by default, `check_newer_vagrant_box` which if enabled would have returned a warning to the user telling them their box is outdated (I think we should probably turn it on, can't recall a good reason as to why I disabled it), and `run_os_update` which prevents `apt-get update` running on startup, this one is disabled to speed the startup and is documented [here](https://github.com/cloudsoft/amp-vagrant#running-os-updates).

Re updating underlying OS, I agree that a jump to Xenial is desired, I've held off doing so as it still doesn't play nicely with Vagrant/Virtualbox for me and [others](https://github.com/mitchellh/vagrant/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+xenial)

**Comment by murdoaird** [comment]
Hi @johnmccabe - many thanks. Am sorted now. Will leave the issue open until I implement your suggestion.
